(function installResearchCaseDeepDives(){
  const $=(q,c=document)=>c.querySelector(q), $$=(q,c=document)=>[...c.querySelectorAll(q)];
  const zh=()=>document.documentElement.lang!=='en';
  const bi=(a,b)=>`<span class="story-zh">${a}</span><span class="story-en">${b}</span>`;
  const research=$('#research');
  if(!research||$('#case-nmrnet')) return;

  function observe(el){if(!el)return;if('IntersectionObserver'in window){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('is-visible')}),{threshold:.2});o.observe(el)}else el.classList.add('is-visible')}
  function section(id,no,kicker,title,lead,body){const s=document.createElement('section');s.id=id;s.className='section snap-section story-section case-section';s.innerHTML=`<div class="section-no">${no}</div><div class="story-copy story-reveal"><div class="story-kicker">${kicker}</div><h2>${title}</h2>${lead?`<p class="lead compact">${lead}</p>`:''}</div>${body}`;research.insertAdjacentElement('beforebegin',s);observe(s);return s}
  function linksHTML(item){return `<div class="case-links">${(item.links||[]).map(l=>`<a href="${l.url}" target="_blank" rel="noopener">${l.label} ↗</a>`).join('')}</div>`}
  function badgeHTML(item){return `<div class="case-badge-row"><span class="case-badge paper">${item.status}</span><span class="case-badge">${item.venue}</span></div>`}

  fetch('data/research.json?v=20260824c').then(r=>r.json()).then(items=>{
    const byId=id=>items.find(x=>x.id===id);
    const nmr=byId('nmrnet'),elyte=byId('op-elyte'),cat=byId('catkg');
    if(nmr) buildNMR(nmr);
    if(elyte) buildElyte(elyte);
    if(cat) buildCatKG(cat);
    setTimeout(()=>window.dispatchEvent(new Event('scroll')),0);
  }).catch(e=>console.warn('case deep-dives',e));

  function buildNMR(item){
    const stepsZh=['先把目标原子周围的三维局域环境交给模型。','SE(3) Transformer 用对三维旋转/平移更合适的方式处理原子环境。','先在较大数据上预训练，再针对具体 NMR 数据集微调。','最终输出原子级 chemical shift；论文同时建立了覆盖液态与固态数据的 benchmark。'];
    const stepsEn=['Represent the 3D local environment around the target atom.','Use an SE(3) Transformer to model atomic environments with geometry-aware symmetry handling.','Pretrain on larger data, then fine-tune for specific NMR datasets.','Predict atom-level chemical shifts; the paper also establishes a benchmark covering liquid- and solid-state data.'];
    const s=section('case-nmrnet','C1 / CASE','PUBLISHED CASE · NMRNET',bi('NMRNet：3D 几何怎样进入真实谱学任务？','NMRNet: how does 3D geometry enter a real spectroscopy task?'),bi('这一页不背网络结构。只看一个研究问题怎样经过 3D 表示、等变建模和迁移学习，最后变成可评测的 chemical-shift prediction。','Do not memorize architecture details. Follow how a spectroscopy problem becomes a 3D representation, a symmetry-aware model and an evaluated chemical-shift prediction.'),`
      <div class="case-grid story-reveal"><div class="case-stage"><div class="case-visual-title">REDRAWN TEACHING WORKFLOW · BASED ON PAPER FIG. 1</div><div class="case-flow"><div class="case-flow-node active"><small>01 · INPUT</small><strong>3D atomic environment</strong></div><div class="case-flow-node"><small>02 · MODEL</small><strong>SE(3) Transformer</strong></div><div class="case-flow-node"><small>03 · LEARNING</small><strong>pretrain → fine-tune</strong></div><div class="case-flow-node"><small>04 · OUTPUT</small><strong>chemical shift δ</strong></div></div><div class="nmr-viz"><div class="nmr-env stage-1"><div class="nmr-ring r1"></div><div class="nmr-ring r2"></div><span class="nmr-atom center">C*</span><span class="nmr-atom a1">H</span><span class="nmr-atom a2">O</span><span class="nmr-atom a3">C</span><span class="nmr-atom a4">H</span></div><div class="nmr-model-stack"><div class="nmr-model-card"><small>GEOMETRY</small><strong>local environment</strong></div><div class="nmr-model-card"><small>TRANSFER</small><strong>pretrain → fine-tune</strong></div><div class="nmr-output"><small>PREDICTED SHIFT</small><strong>δ</strong></div></div></div></div><aside class="case-panel">${badgeHTML(item)}<p class="case-question">${bi(item.question,item.questionEn)}</p><div class="case-step-list">${stepsZh.map((x,i)=>`<button class="case-step-button ${i===0?'active':''}" data-i="${i}" type="button"><small>STEP ${i+1}</small><strong>${x.split('。')[0]}</strong></button>`).join('')}</div><div class="case-takeaway"></div>${linksHTML(item)}<p class="case-note">${bi('流程图为课程根据论文方法重画，不是原论文 Figure 的复制。','Workflow redrawn for teaching from the published method; it is not a reproduced paper figure.')}</p></aside></div>`);
    const nodes=$$('.case-flow-node',s),modelCards=$$('.nmr-model-card',s),env=$('.nmr-env',s),take=$('.case-takeaway',s);let step=0;
    function render(){nodes.forEach((n,i)=>{n.classList.toggle('active',i===step);n.classList.toggle('dim',i>step+1)});modelCards.forEach((n,i)=>n.classList.toggle('active',(step===1&&i===0)||(step===2&&i===1)));env.className='nmr-env '+(step===0?'stage-1':step>=1?'stage-2':'');take.textContent=(zh()?stepsZh:stepsEn)[step];$$('.case-step-button',s).forEach((b,i)=>b.classList.toggle('active',i===step))}
    $$('.case-step-button',s).forEach(b=>b.addEventListener('click',()=>{step=+b.dataset.i;render()}));render();$('#lang-toggle')?.addEventListener('click',()=>requestAnimationFrame(render));
  }

  function buildElyte(item){
    const stepsZh=['从很大的电解液组成空间出发：论文使用 2300+ solvents 与 20 salts 的数据库来随机组合体系。','并发学习反复执行 training → exploration → screening → labeling，用新的 DFT 标注补充模型最需要的数据。','训练得到面向电解液体系的 uMLP，并用 MLMD 扩展可模拟时间尺度。','利用轨迹计算密度、溶剂化结构、黏度、离子电导率等性质，并进一步分析 Li⁺ coordination dynamics。'];
    const stepsEn=['Start from a large electrolyte-composition space built from databases of 2300+ solvents and 20 salts.','Concurrent learning cycles through training, exploration, screening and labeling so new DFT data target configurations the model needs.','Train a domain-oriented uMLP and use it for machine-learning molecular dynamics.','Use trajectories to compute density, solvation structure, viscosity, ionic conductivity and analyze Li+ coordination dynamics.'];
    const chips=['carbonate','ether','nitrile','sulfone','heterocycle','LiPF₆','LiFSI','LiTFSI','LiBF₄','LiNO₃'];
    const positions=[[7,18],[30,12],[55,19],[76,11],[16,58],[44,55],[68,52],[82,68],[31,78],[59,79]];
    const s=section('case-elyte','C2 / CASE','PUBLISHED CASE · ATOMISTIC ML',bi('电解液 uMLP：AI 怎样从 property prediction 走到 molecular simulation？','Electrolyte uMLP: how does AI move from property prediction to molecular simulation?'),bi('这里模型不直接回答“电导率是多少”。它先学习原子势能面，再驱动长时间尺度 MLMD，宏观性质从轨迹中计算出来。','Here the model does not directly answer “what is the conductivity?” It learns an atomistic potential, drives MLMD, and properties are computed from trajectories.'),`
      <div class="case-grid story-reveal"><div class="case-stage"><div class="case-visual-title">REDRAWN TEACHING WORKFLOW · BASED ON PAPER FIG. 1c</div><div class="case-flow"><div class="case-flow-node active"><small>01 · SPACE</small><strong>random electrolyte compositions</strong></div><div class="case-flow-node"><small>02 · DATA</small><strong>concurrent learning + DFT</strong></div><div class="case-flow-node"><small>03 · MODEL</small><strong>uMLP → MLMD</strong></div><div class="case-flow-node"><small>04 · SCIENCE</small><strong>structure & properties</strong></div></div><div class="elyte-space">${chips.map((c,i)=>`<span class="elyte-chip ${c.startsWith('Li')?'salt':'solvent'}" style="left:${positions[i][0]}%;top:${positions[i][1]}%">${c}</span>`).join('')}</div><div class="concurrent-loop"><div class="concurrent-step active">Train</div><div class="concurrent-step">Explore</div><div class="concurrent-step">Screen</div><div class="concurrent-step">Label / DFT</div></div><div class="mlmd-strip"><strong>uMLP → MLMD</strong><div class="mlmd-particles">${'<i></i>'.repeat(10)}</div><span>trajectory</span></div><div class="elyte-output-grid"><div class="elyte-output">density</div><div class="elyte-output">solvation</div><div class="elyte-output">viscosity</div><div class="elyte-output">conductivity</div></div><div class="case-fact-row"><div class="case-fact"><small>SOLVENT DATABASE</small><strong>2300+</strong></div><div class="case-fact"><small>SALTS</small><strong>20</strong></div><div class="case-fact"><small>CONCURRENT-LEARNING ITERATIONS</small><strong>91</strong></div><div class="case-fact"><small>CONFIGURATIONS</small><strong>≈160k</strong></div></div></div><aside class="case-panel">${badgeHTML(item)}<p class="case-question">${bi(item.question,item.questionEn)}</p><div class="case-step-list">${stepsZh.map((x,i)=>`<button class="case-step-button ${i===0?'active':''}" data-i="${i}" type="button"><small>STEP ${i+1}</small><strong>${['chemical space','concurrent learning','uMLP + MLMD','properties + mechanism'][i]}</strong></button>`).join('')}</div><div class="case-takeaway"></div>${linksHTML(item)}<p class="case-note">${bi('2300+ solvents、20 salts、91 次并发学习与约 160k configurations 均来自论文正文。','2300+ solvents, 20 salts, 91 concurrent-learning iterations and about 160k configurations are reported in the paper.')}</p></aside></div>`);
    const flow=$$('.case-flow-node',s),loop=$$('.concurrent-step',s),space=$('.elyte-space',s),take=$('.case-takeaway',s);let step=0;
    function render(){flow.forEach((n,i)=>{n.classList.toggle('active',i===step);n.classList.toggle('dim',i>step+1)});loop.forEach((n,i)=>n.classList.toggle('active',step===1&&i===Math.floor((Date.now()/700)%4)));space.classList.toggle('active',step===0);take.textContent=(zh()?stepsZh:stepsEn)[step];$$('.case-step-button',s).forEach((b,i)=>b.classList.toggle('active',i===step))}
    let timer=setInterval(()=>{if(step===1)render()},700);$$('.case-step-button',s).forEach(b=>b.addEventListener('click',()=>{step=+b.dataset.i;render()}));render();$('#lang-toggle')?.addEventListener('click',()=>requestAnimationFrame(render));
  }

  function buildCatKG(item){
    const stepsZh=['先定义催化知识 schema，再用 LLM 辅助从文献中抽取反应、反应物、催化剂、溶剂和产物等结构化信息。','把结构化数据写入 Cat-KG；论文报告其覆盖 15,881 篇催化文献与 27,760 个热催化反应。','针对目标产物查询候选多步路径，再用 relay-catalysis 专家规则进行筛选和排序。','最后才让 LLM 把结构化路径和条件转成化学家可读的描述；关键 ID 可回溯到 KG 与原文献，仍需人工验证重要结果。'];
    const stepsEn=['Define a catalysis schema, then use an LLM-assisted workflow to extract structured reactions, reactants, catalysts, solvents and products from literature.','Store the structured data in Cat-KG; the paper reports 15,881 catalysis publications and 27,760 thermocatalytic reactions.','Query candidate multistep paths for a target product, then filter and rank them with expert relay-catalysis scoring rules.','Only then use an LLM to render structured paths and conditions for chemists; IDs remain traceable to the KG and literature, and consequential results still require manual verification.'];
    const s=section('case-catkg','C3 / CASE','PUBLISHED CASE · KNOWLEDGE + LLM',bi('Cat-KG + LLM：为什么“结构化知识”比直接问大模型更可靠？','Cat-KG + LLM: why can structured knowledge be more reliable than directly asking an LLM?'),bi('这里 LLM 不是从头“想”出催化路线。可靠性来自 literature → structured KG → chemistry rules → traceable output 这条受约束的链。','The LLM does not invent a catalytic pathway from scratch. Reliability comes from a constrained chain: literature → structured KG → chemistry rules → traceable output.'),`
      <div class="case-grid story-reveal"><div class="case-stage"><div class="case-visual-title">REDRAWN TEACHING WORKFLOW · BASED ON PAPER FIGS. 1 & 4</div><div class="catkg-pipeline"><div class="catkg-step active"><small>01</small><strong>Literature</strong></div><div class="catkg-step"><small>02</small><strong>LLM extraction</strong></div><div class="catkg-step"><small>03</small><strong>Cat-KG</strong></div><div class="catkg-step"><small>04</small><strong>Query + rules</strong></div><div class="catkg-step"><small>05</small><strong>Readable output</strong></div></div><div class="kg-stage"><span class="kg-node catalyst" style="left:7%;top:18%">Catalyst A</span><span class="kg-node reaction" style="left:31%;top:18%">Reaction 1</span><span class="kg-node product" style="left:57%;top:18%">Intermediate</span><span class="kg-node reaction" style="left:42%;top:52%">Reaction 2</span><span class="kg-node catalyst" style="left:73%;top:53%">Catalyst B</span><span class="kg-node product" style="left:74%;top:19%">Target</span><div class="kg-path"><span>source IDs</span><b>→</b><span>candidate path</span><b>→</b><span>chemistry score</span><b>→</b><span>trace back</span></div></div><div class="case-fact-row"><div class="case-fact"><small>CATALYSIS PUBLICATIONS</small><strong>15,881</strong></div><div class="case-fact"><small>THERMOCATALYTIC REACTIONS</small><strong>27,760</strong></div></div><div class="trace-strip">Traceability: structured recommendation → reaction IDs → Cat-KG entries → original literature.</div></div><aside class="case-panel">${badgeHTML(item)}<p class="case-question">${bi(item.question,item.questionEn)}</p><div class="case-step-list">${stepsZh.map((x,i)=>`<button class="case-step-button ${i===0?'active':''}" data-i="${i}" type="button"><small>STEP ${i+1}</small><strong>${['extract','structure','search + score','render + verify'][i]}</strong></button>`).join('')}</div><div class="case-takeaway"></div>${linksHTML(item)}<p class="case-note">${bi('论文明确指出，即使使用结构化数据约束 LLM，重要路径仍应沿 ID 回溯并人工检查。','The paper explicitly notes that important pathways should still be manually checked by tracing IDs back to Cat-KG entries and publications.')}</p></aside></div>`);
    const flow=$$('.catkg-step',s),nodes=$$('.kg-node',s),take=$('.case-takeaway',s);let step=0;
    function render(){flow.forEach((n,i)=>n.classList.toggle('active',Math.min(step+1,4)===i||step===0&&i===0));nodes.forEach((n,i)=>n.classList.toggle('active',step>=1&&((i+step)%3===0||step>=2)));take.textContent=(zh()?stepsZh:stepsEn)[step];$$('.case-step-button',s).forEach((b,i)=>b.classList.toggle('active',i===step))}
    $$('.case-step-button',s).forEach(b=>b.addEventListener('click',()=>{step=+b.dataset.i;render()}));render();$('#lang-toggle')?.addEventListener('click',()=>requestAnimationFrame(render));
  }
})();
