(function installGeneralizationPage(){
  const $=(q,c=document)=>c.querySelector(q),$$=(q,c=document)=>[...c.querySelectorAll(q)];
  const zh=()=>document.documentElement.lang!=='en';const text=(el,cn,en)=>{if(el)el.textContent=zh()?cn:en};
  const s=$('#play');if(!s)return;$('#generalization-curves')?.remove();$('#unseen-vocabulary')?.remove();
  if(!document.querySelector('link[data-generalization-page]')){const l=document.createElement('link');l.rel='stylesheet';l.href='css/course/training/generalization.css?v=20260826b';l.dataset.generalizationPage='1';document.head.appendChild(l)}
  function polishedFit(){
    try{
      const canvas=$('#fit-canvas',s);if(!canvas||typeof pts==='undefined'||typeof testPts==='undefined'||typeof polyfit==='undefined'||typeof pred==='undefined')return;
      const c=canvas.getContext('2d'),deg=Number($('#degree',s)?.value||2),coef=polyfit(pts,deg),W=canvas.width,H=canvas.height;
      const X=x=>52+(x+1)/2*(W-104),yMin=-.55,yMax=1.02,Y=y=>H-40-((y-yMin)/(yMax-yMin))*(H-80);
      c.clearRect(0,0,W,H);c.fillStyle='#fffdf7';c.fillRect(0,0,W,H);
      c.save();c.strokeStyle='rgba(38,51,47,.075)';c.lineWidth=1;c.setLineDash([2,8]);for(let i=1;i<5;i++){const y=34+i*(H-68)/5;c.beginPath();c.moveTo(44,y);c.lineTo(W-34,y);c.stroke()}for(let i=1;i<6;i++){const x=44+i*(W-78)/6;c.beginPath();c.moveTo(x,28);c.lineTo(x,H-30);c.stroke()}c.restore();
      const trace=(stroke,width)=>{c.save();c.strokeStyle=stroke;c.lineWidth=width;c.lineCap='round';c.lineJoin='round';c.beginPath();let started=false;for(let i=0;i<=400;i++){const x=-1+2*i/400,y=pred(coef,x),py=Y(y);if(!Number.isFinite(py))continue;if(started)c.lineTo(X(x),py);else{c.moveTo(X(x),py);started=true}}c.stroke();c.restore()};
      trace('rgba(47,118,131,.14)',12);trace('#2f7683',4.5);
      const dot=(x,y,fill)=>{const px=X(x),py=Y(y);c.beginPath();c.arc(px,py,8.3,0,Math.PI*2);c.fillStyle='rgba(255,250,240,.95)';c.fill();c.beginPath();c.arc(px,py,5.2,0,Math.PI*2);c.fillStyle=fill;c.fill()};pts.forEach(([x,y])=>dot(x,y,'#26332f'));testPts.forEach(([x,y])=>dot(x,y,'#d87558'));
    }catch(e){}
  }
  function queueFit(){requestAnimationFrame(()=>requestAnimationFrame(polishedFit))}
  function apply(){const no=$('.section-no',s);if(no)no.textContent='02F / GENERALIZATION';const title=$('h2',s);text(title,'欠拟合和过拟合，差别在哪里？','What is the difference between underfitting and overfitting?');$('.lead',s)?.remove();$('.hand',s)?.remove();let k=$('.p32-kicker',s);if(!k){k=document.createElement('div');k.className='story-kicker p32-kicker';title?.insertAdjacentElement('beforebegin',k)}text(k,'模型不只要拟合训练数据，还要对留出数据有效','A model must work beyond its training data');const pg=$('.compact-playground',s);if(!pg)return;text($('label span',pg),'模型复杂度','Model complexity');const metrics=$('.metrics',pg);if(metrics&&!metrics.dataset.p32Ready){const deg=$('#degree',s)?.value||'2';metrics.innerHTML=`<span class="p32-degree">${zh()?'模型复杂度':'Model complexity'} <strong id="degree-value">${deg}</strong></span><span id="fit-status"></span>`;metrics.dataset.p32Ready='1'}else if(metrics){const labelEl=$('.p32-degree',metrics);if(labelEl)labelEl.childNodes[0].nodeValue=(zh()?'模型复杂度 ':'Model complexity ')}if(!$('.p32-fit-legend',pg)){const legend=document.createElement('div');legend.className='p32-fit-legend';legend.innerHTML='<span><i class="train"></i><b></b></span><span><i class="heldout"></i><b></b></span><span><i class="curve"></i><b></b></span>';pg.appendChild(legend)}const lbs=$$('b',$('.p32-fit-legend',pg));text(lbs[0],'训练样本','Training samples');text(lbs[1],'留出样本','Held-out samples');text(lbs[2],'当前模型','Current model');if(!$('.p32-fit-explain',s)){const box=document.createElement('div');box.className='p32-fit-explain';box.innerHTML='<article data-state="under"><strong></strong><p></p><b></b></article><article data-state="good"><strong></strong><p></p><b></b></article><article data-state="over"><strong></strong><p></p><b></b></article>';pg.insertAdjacentElement('afterend',box)}const cards=$$('.p32-fit-explain article',s),content=zh()?[["欠拟合","模型太简单或训练不充分，连训练数据里的主要规律都没有学好。","处理：增加有效表示或模型能力，并确认训练充分"],["较合适","训练数据和留出数据都保持较好表现，学到的规律更可能迁移。","目标：留出误差低，而且和训练误差差距不过大"],["过拟合","训练数据越来越好，留出数据却开始变差。","处理：更多数据、降低复杂度、正则化或早停"]]:[["Underfitting","The model is too simple or insufficiently trained, so even the main training pattern is missed.","Fix: improve representation or capacity and train sufficiently"],["Reasonable fit","Training and held-out performance stay good together, suggesting the learned pattern transfers.","Goal: low held-out error without a large train–held-out gap"],["Overfitting","Training keeps improving while held-out performance worsens.","Fix: more data, lower complexity, regularization, or early stopping"]];cards.forEach((c,i)=>{c.querySelector('strong').textContent=content[i][0];c.querySelector('p').textContent=content[i][1];c.querySelector('b').textContent=content[i][2]});update();queueFit()}
  function update(){const deg=Number($('#degree',s)?.value||2),state=deg<=1?'under':deg<=4?'good':'over';$$('.p32-fit-explain article',s).forEach(c=>c.classList.toggle('active',c.dataset.state===state));const status=$('#fit-status',s);if(status)status.textContent=zh()?(state==='under'?'当前：欠拟合':state==='good'?'当前：泛化较好':'当前：过拟合风险'):(state==='under'?'Current: underfitting':state==='good'?'Current: reasonable generalization':'Current: overfitting risk');queueFit()}
  if(!s.dataset.p32Bound){s.dataset.p32Bound='1';$('#degree',s)?.addEventListener('input',()=>requestAnimationFrame(update))}
  try{if(typeof drawFit==='function')drawFit=polishedFit}catch(e){}
  apply();window.addEventListener('resize',queueFit);document.getElementById('lang-toggle')?.addEventListener('click',()=>requestAnimationFrame(()=>requestAnimationFrame(apply)));
})();
