(function installHoldoutPage(){
  const $=(q,c=document)=>c.querySelector(q),$$=(q,c=document)=>[...c.querySelectorAll(q)];
  const zh=()=>document.documentElement.lang!=='en';
  const text=(el,cn,en)=>{if(el)el.textContent=zh()?cn:en};
  const s=$('#holdout-screen');if(!s)return;
  $('#data-split')?.remove();
  if(!document.querySelector('link[data-holdout-page]')){const l=document.createElement('link');l.rel='stylesheet';l.href='css/course/training/holdout.css?v=20260826c';l.dataset.holdoutPage='1';document.head.appendChild(l)}
  const splitOrder=Array.from({length:100},(_,i)=>(i*37)%100);
  function header(){text($('.section-no',s),'02E / 数据划分','02E / DATA SPLIT');text($('.story-kicker',s),'为什么必须留出数据','WHY HOLD OUT DATA');text($('.story-copy h2',s),'训练数据为什么要分三份？','Why split data into train, validation and test?');$('.story-copy .lead',s)?.remove()}
  function ensure(){let lab=$('.p30-merged-split',s);if(lab)return lab;$('.holdout-lab',s)?.remove();lab=document.createElement('div');lab.className='p30-merged-split story-reveal';lab.innerHTML=`<div class="p30-plan-tabs"><button type="button" class="p30-plan active" data-mode="all"><strong></strong><span></span></button><button type="button" class="p30-plan" data-mode="split"><strong></strong><span></span></button></div><div class="p30-board-panel"><div class="p30-plan-copy"><strong></strong><p></p></div><div class="p30-board" aria-label="100 samples"></div><div class="p30-legend"><span><i class="train"></i><b class="train-label"></b><em class="train-count">100</em></span><span><i class="val"></i><b class="val-label"></b><em class="val-count">0</em></span><span><i class="test"></i><b class="test-label"></b><em class="test-count">0</em></span></div><div class="p30-conclusion"></div></div>`;s.appendChild(lab);const board=$('.p30-board',lab);for(let i=0;i<100;i++){const d=document.createElement('i');d.className='p30-dot train';d.style.setProperty('--delay',`${(i%10)*10+Math.floor(i/10)*7}ms`);board.appendChild(d)}$$('.p30-plan',lab).forEach(b=>b.addEventListener('click',()=>render(b.dataset.mode,true)));return lab}
  function render(mode,animate=false){const lab=ensure();s.dataset.p30Mode=mode;const plans=$$('.p30-plan',lab);plans.forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));text($('strong',plans[0]),'方案 A · 全部训练','Plan A · train on everything');text($('span',plans[0]),'100 个样本全部进入训练集','All 100 samples enter training');text($('strong',plans[1]),'方案 B · 8 : 1 : 1','Plan B · 8 : 1 : 1 split');text($('span',plans[1]),'训练 80 · 验证 10 · 测试 10','Train 80 · validation 10 · test 10');text($('.train-label',lab),'训练集','Train');text($('.val-label',lab),'验证集','Validation');text($('.test-label',lab),'测试集','Test');const dots=$$('.p30-dot',lab);dots.forEach(d=>{d.classList.remove('train','val','test','pop');d.classList.add('train')});if(mode==='split'){splitOrder.forEach((idx,pos)=>{const d=dots[idx];d.classList.remove('train');d.classList.add(pos<80?'train':pos<90?'val':'test');if(animate)d.classList.add('pop')});$('.train-count',lab).textContent='80';$('.val-count',lab).textContent='10';$('.test-count',lab).textContent='10';text($('.p30-plan-copy strong',lab),'让不同数据承担不同职责','Give different data different roles');text($('.p30-plan-copy p',lab),'训练集学习参数，验证集帮助选择设置，测试集尽量留到最后做独立检查。','Training learns parameters, validation guides choices, and test is kept for the final independent check.');text($('.p30-conclusion',lab),'真正想知道的是：没参与训练和调参的新数据，还能不能预测','The real question: does the model still work on data not used for fitting or tuning?')}else{$('.train-count',lab).textContent='100';$('.val-count',lab).textContent='0';$('.test-count',lab).textContent='0';text($('.p30-plan-copy strong',lab),'全部训练，看起来最不浪费数据','Training on everything looks efficient');text($('.p30-plan-copy p',lab),'但如果最后仍在这 100 个样本上打分，我们只知道模型对“做过的题”表现怎样。','But scoring on the same 100 samples only tells us how the model performs on questions it already saw.');text($('.p30-conclusion',lab),'没有独立留出数据，就没有独立的泛化证据','Without held-out data, there is no independent evidence of generalization')}}
  function apply(){header();render(s.dataset.p30Mode||'all',false)}apply();document.getElementById('lang-toggle')?.addEventListener('click',()=>setTimeout(apply,100));
})();
